// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Studen.proto

package com.netty.study.eigth.grpc.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
