// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Studen.proto

package com.netty.study.eigth.grpc.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.netty.study.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.netty.study.eigth.grpc.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.netty.study.proto.StudentResponse studentResponse = 1;</code>
   */
  com.netty.study.eigth.grpc.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.netty.study.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.netty.study.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.netty.study.eigth.grpc.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.netty.study.proto.StudentResponse studentResponse = 1;</code>
   */
  com.netty.study.eigth.grpc.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
