// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Studen.proto

package com.netty.study.eigth.grpc.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
